
namespace Platformer
{
    public enum ETexts
    {
        Enter,
        Exit,
        Next,
        PullLever,
        KindleFire,
        RemoveObstacle,
        Talk,
        TalkToMom,
        TalkToMomAgain,
        VillageCommoner,
        UpgradeHealthTip,
        UpgradeHealthTitle,
        SwitchOn,
        DestinationTheVillage,
        DestinationWesternForest,
        DestinationMountains,
        DestinationCaveLabyrinth,
        DestinationLumbermill,
        DestinationWolfTrail,

        //Menu items
        English,
        Russian,

        LifeSpentMessage,
        GameOverMessage,
        TryAgain,
        ToMenu,

        //Quest Dialogues
        PieDialogue1,
        //MQ1First :
        DialoguePie1_1,
        DialoguePie1_2,
        DialoguePie1_3,
        DialoguePie1_4,
        DialoguePie1_5,
        DialoguePie1_6,
        //MQ1Second :
        DialoguePie1_7,
        DialoguePie1_8,
        DialoguePie1_9,

        FamilyMonologue,
        Family_1,
        Family_2,
        Family_3,
        Family_4,

        FatherDialogue,
        Father_1,
        Father_2,
        Father_3,
        Father_4,
        Father_5,
        Father_6,
        Father_7,
        Father_8,

        PieDialogue2,
        DialoguePie2_1,
        DialoguePie2_2,
        DialoguePie2_3,
        DialoguePie2_4,
        DialoguePie2_5,
        DialoguePie2_6,

        UpgradeHealth1_1,
        UpgradeHealth1_2,
        UpgradeHealth1_3,
        UpgradeHealth1_4,
        UpgradeHealth1_5,
        UpgradeHealth2_1,
        UpgradeHealth2_2,
        UpgradeHealth2_3,

        BlacksmithTitle1,
        Blacksmith1_1,
        Blacksmith1_2,
        Blacksmith1_3,
        Blacksmith1_4,
        Blacksmith1_5,
        Blacksmith2_1,
        Blacksmith2_2,
        Blacksmith2_3,
        Blacksmith2_4,

        Commoner1_1,
        Commoner1_2,
        CommonerSecret,
        WomanCandy,
        GatekeeperTitle,
        Gatekeeper1_1,
        Gatekeeper1_2,
        ShopkeeperTitle,
        Shopkeeper1,

        HermitTitle,
        Hermit1_1,
        Hermit1_2,
        Hermit1_3,
        Hermit1_4,
        Hermit2,
    }
}