
namespace Platformer
{
    public enum ETexts
    {
        PieDialogue1_Title,
        DialoguePie1_1,
        DialoguePie1_2,
        DialoguePie1_3,
        DialoguePie1_4,
        DialoguePie1_5,
        DialoguePie1_6,
        DialoguePie1_7,
        DialoguePie1_8,
        DialoguePie1_9,

        FamilyMonologue_Title,
        Family_1,
        Family_2,
        Family_3,
        Family_4,

        FatherDialogue_Title,
        Father_1,
        Father_2,
        Father_3,
        Father_4,
        Father_5,
        Father_6,
        Father_7,
        Father_8,

        PieDialogue2_Title,
        DialoguePie2_1,
        DialoguePie2_2,
        DialoguePie2_3,
        DialoguePie2_4,
        DialoguePie2_5,
        DialoguePie2_6,

        UpgradeHealth_Title,
        UpgradeHealth1_1,
        UpgradeHealth1_2,
        UpgradeHealth1_3,
        UpgradeHealth1_4,
        UpgradeHealth1_5,
        UpgradeHealth2_1,
        UpgradeHealth2_2,
        UpgradeHealth2_3,

        Blacksmith_Title1,
        Blacksmith1_1,
        Blacksmith1_2,
        Blacksmith1_3,
        Blacksmith1_4,
        Blacksmith1_5,
        Blacksmith2_1,
        Blacksmith2_2,
        Blacksmith2_3,
        Blacksmith2_4,

        Commoner_Title,
        VillageElevator_1,
        VillageElevator_2,
        GatekeeperWarning,
        CommonerSecret,
        WomanCandy,
        Gatekeeper_Title,
        Gatekeeper1_1,
        Gatekeeper1_2,
        Shopkeeper_Title,
        Shopkeeper1,
        Commoner3, //Klaus' wife

        Hermit_Title,
        Hermit1_1,
        Hermit1_2,
        Hermit1_3,
        Hermit1_4,
        Hermit2,

        BrokenLeverTip_Title,
        BrokenLever1,
        BrokenLeverInCave_Title,
        BrokenLeverInCave1,
        BrokenLeverInCave_HandleNotFound,
        BrokenLeverInCave_HandleFound,

        DisturbSpirit_Title,
        DisturbSpirit1,
        DisturbSpirit2,
        DisturbSpirit3,
        DisturbSpirit4,

        HollyMolly_Title,
        HollyMolly1_1,
        HollyMolly1_2,
        HollyMolly1_3,
        HollyMolly1_4,
        HollyMolly1_5,
        HollyMolly1_6,
        HollyMolly1_7,
        HollyMolly1_8,
        HollyMolly1_9,
        HollyMolly1_10,
        HollyMolly1_11,

        ForsakenCamp_Title,
        ForsakenCamp_1,

        Assistant_Title,
        Assistant_frog1,
        Assistant_frog2_1,
        Assistant_frog2_2,
        Assistant_frog3,
        Assistant_frog4,
        Assistant_frog5,
        Assistant_frog6,
        Assistant_frog7,

        Assistant_tower1,
        Assistant_tower2_1,
        Assistant_tower2_2,
        Assistant_tower3,
        Assistant_tower4,
        Assistant_tower5,
        Assistant_tower6,

        Guide_v01_Title,
        Guide_v01_1,
        Guide_v01_2,
        Guide_v01_3,
        Guide_v01_remind,
    }
}